name: Publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x 
    - name: Cache
      uses: actions/cache@v1.0.3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Setup Jekyll
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build
      run: |
        if [[ -z "${SRC}" ]]; then
          SRC=$(find . -name _config.yml -exec dirname {} \;)
        fi

        echo "#################################################"
        echo "Source for the Jekyll site is set to ${SRC}"

        bundle exec jekyll build -s ${SRC} -d build
        echo "#################################################"
        echo "Jekyll build done"
        
        cd build

        # No need to have GitHub Pages to run Jekyll
        touch .nojekyll

    - name: Publish
      run: |
        echo "#################################################"
        echo "Now publishing"
        if [[ -z "${JEKYLL_PAT}" ]]; then
          TOKEN=${{secrets.GITHUB_TOKEN}}
        else 
          TOKEN=${{secrets.JEKYLL_PAT}}
        fi
        
        remote_branch="gh-pages"

        if [ "${GITHUB_REF}" == "refs/heads/${remote_branch}" ]; then
          echo "Cannot publish on branch ${remote_branch}"
          exit 1
        else
          echo "Pushing on branch ${remote_branch}"
        fi

        cd build
        
        remote_repo="https://${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" && \
        git init && \
        git config user.name "${GITHUB_ACTOR}" && \
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
        git add . && \
        git commit -m 'jekyll build from Action' && \
        git push --force $remote_repo master:$remote_branch && \
        rm -fr .git && \
        cd ..
